### ISSUE TITLE
missing namespace in triage report

### ISSUE THREAD

**Issue by survivant** [emirozer/kubectl-doctor#19]
I have my applications deployed in multiple namespaces (CICD), but in the report, the namespace is missing. Will be useful to know.

````
---
 TriageReport:
- Resource: Endpoints
  AnomalyType: Found orphaned endpoints!
  Anomalies:
  - discovery-twin-neo4j-1
  - discovery-twin-neo4j-2
  - discovery-twin-neo4j-3
  - discovery-twin-neo4j-4
  - discovery-twin-neo4j-5
  - production-manager
  - production-manager-influxdb
  - production-manager-mariadb
  - production-wui-dev
  - vault
  - vault-master
  - vault-master-headless
  - discovery-twin-neo4j-0
  - discovery-twin-neo4j-1
  - discovery-twin-neo4j-2
  - discovery-twin-neo4j-3
  - discovery-twin-neo4j-4
  - discovery-twin-neo4j-5
  - event-manager-master
  - event-manager-master-headless
  - twin-neo4j
  - vault-master
  - vault-master-headless
  - discovery-twin-neo4j-1
  - discovery-twin-neo4j-2
  - discovery-twin-neo4j-3
  - discovery-twin-neo4j-4
  - discovery-twin-neo4j-5
  - twin-api-service-feature-test
  - application-server-aa627786a531-mariadb
  - cms-client
  - diagnostic-manager
  - discovery-twin-neo4j-1
  - discovery-twin-neo4j-2
  - discovery-twin-neo4j-3
  - discovery-twin-neo4j-4
  - discovery-twin-neo4j-5
  - event-manager
  - event-manager-master
  - production-manager
  - production-manager-mariadb
  - service-cp-control-center
  - openebs.io-local
  - monitoring-prometheus-node-exporter
  - monitoring-prometheus-node-exporter
````
